apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-config
  namespace: k8s-program
data:
  RESOURCES_DB_URL: "resource-db-service"
  RESOURCES_DB_PORT: "5432"
  SONGS_MS_URL: "song-service"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_GENERATE_DDL: "false"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_SERVLET_DISPATCHERSERVLET: "DEBUG"
  resource-ddl.sql: |
    CREATE TABLE resources (
        id SERIAL PRIMARY KEY,
        blob BYTEA
    );
