apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
  labels:
    role: songs-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-pvc
  labels:
    role: songs-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  