apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-app
  labels:
    app: songs-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: songs-app
  template:
    metadata:
      name: songs-app
      labels:
        app: songs-app
    spec:
      containers:
        - name: songs-app
          image: songs-image:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: song-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases-secret
                  key: password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: databases-secret
                  key: username
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 20
          volumeMounts:
            - mountPath: /mnt/data
              name: songs-pv-storage
      restartPolicy: Always
      volumes:
        - name: songs-pv-storage
          persistentVolumeClaim:
            claimName: songs-pvc

      