apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-app
  labels:
    app: resources-app
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-app
  template:
    metadata:
      name: resources-app
      labels:
        app: resources-app
    spec:
      containers:
        - name: resources-app
          image: resources-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: RESOURCES_DB_URL
              value: resource-db-service
            - name: RESOURCES_DB_PORT
              value: "5432"
            - name: SONGS_MS_URL
              value: song-service

      restartPolicy: Always
      