apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: k8s-program
spec:
  selector:
    app: songs-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
  